exports.GET_MESSAGE_FROM_INTERLOCUTOR = 'GET_MESSAGE_FROM_INTERLOCUTOR';
exports.SET_MESSAGES_VIEWED_BY_RECIPIENT = 'SET_MESSAGES_VIEWED_BY_RECIPIENT';
exports.SET_ONLINE_STATUS = 'SET_ONLINE_STATUS';
exports.BOOK_APPOINTMENT_BY_CUSTOMER = 'BOOK_APPOINTMENT_BY_CUSTOMER';
exports.CHANGE_APPOINTMENT_STATUS_SOCKET = 'CHANGE_APPOINTMENT_STATUS_SOCKET';
