name: CI/CD

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        redis-version: [6]
        mongodb-version: ['4.4']

    env:
      DB_USER: beaurel
      DB_PASSWORD: beaurel
      DB_CLUSTER: 127.0.0.1:27017
      DB_NAME: test
      DB_AUTH_SOURCE: admin

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: ${{ env.DB_USER }}
          mongodb-password: ${{ env.DB_PASSWORD }}
          mongodb-db: ${{ env.DB_NAME }}

      - name: Mongoimport timezones
        run: mongoimport -u $DB_USER -p $DB_PASSWORD --collection timezones --db test --file ./data/database/timezones.json --authenticationDatabase $DB_AUTH_SOURCE --jsonArray

      - name: Install dependencies
        run: npm ci

      - name: Run jest tests
        run: npm run jest:test
        env:
          PORT: 5000
          NODE_ENV: test
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
          CLIENT_URL: http://localhost:3000
          AUTH_HEADER: Authorization
          JWT_KEY_ACCESS: gjkhgkjgjhgjhkgjh
          JWT_KEY_REFRESH: gtuytuyituiygmbjh
          JWT_KEY_ACCESS_TIME: 15h
          JWT_KEY_REFRESH_TIME: 604800000
          TWILIO_SID: ACsomething
          TWILIO_AUTH_TOKEN: something
          S3_KEY_ID: ${{ secrets.S3_KEY_ID }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_TEST }}

  deploy:
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/beaurel-api
          build-args: |
            PORT=5000
            NODE_ENV=production
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_CLUSTER=${{ secrets.DB_CLUSTER }}
            DB_NAME=${{ secrets.DB_NAME }}
            REDIS_HOST=beaurel-redis
            REDIS_PORT=6379
            CLIENT_URL=http://localhost
            AUTH_HEADER=Authorization
            JWT_KEY_ACCESS=dfghjkpiuytrfvbnmloiuytfdvbnju
            JWT_KEY_REFRESH=dfgytresxcbiugoigiogoun
            JWT_KEY_ACCESS_TIME=15h
            JWT_KEY_REFRESH_TIME=604800000
            IS_SOCKET_IO=true
            TWILIO_SID=ACsomething
            TWILIO_AUTH_TOKEN=something
            S3_KEY_ID=${{ secrets.S3_KEY_ID }}
            S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
            S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME_DEMO }}
