name: CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        redis-version: [6]
        mongodb-version: ['4.4']

    env:
      DB_USER: beaurel
      DB_PASSWORD: beaurel
      DB_CLUSTER: 127.0.0.1:27017
      DB_NAME: test
      DB_AUTH_SOURCE: admin

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: $DB_USER
          mongodb-password: $DB_PASSWORD
          mongodb-db: $DB_NAME

      - name: Mongoimport timezones
        run: mongoimport --jsonArray -p $DB_USER -u $DB_PASSWORD --collection timezones --db test --file ./data/database/timezones.json --authenticationDatabase $DB_AUTH_SOURCE

      - name: Install dependencies
        run: npm ci

      - name: Start api
        run: npm start &
        env:
          PORT: 5000
          NODE_ENV: test
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
          CLIENT_URL: http://localhost:3000
          AUTH_HEADER: Authorization
          JWT_KEY_ACCESS: gjkhgkjgjhgjhkgjh
          JWT_KEY_REFRESH: gtuytuyituiygmbjh
          JWT_KEY_ACCESS_TIME: 15h
          JWT_KEY_REFRESH_TIME: 604800000
          TWILIO_SID: ACsomething
          TWILIO_AUTH_TOKEN: something
          S3_KEY_ID: ${{ secrets.S3_KEY_ID }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
